name: clicli_dark
description: CliCli Dark. clicli 纯黑.

version: 1.0.0+4

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  cached_network_image: any
  flutter_markdown: any
  url_launcher: any
  flutter_downloader: any
  path_provider: any
  flutter_flexible_toast: any
  shared_preferences: any
  event_bus: any
  music_volume: any
  package_info: any

  # chewie
  video_player: any
  screen: any
  open_iconic_flutter: any

flutter:
  uses-material-design: true
  assets:
    - assets/loading.gif
    - assets/error.png
